version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    command: ["sh", "-c", " flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002"]
    ports:
      - 5002:5002
      - 5678:5678
    environment:
      - FLASK_APP=app.py
