version: '3.4'

services:
  youbiketracker:
    image: youbiketracker
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 5002:5002
